### ISSUE TITLE
timeout option is not working.

### ISSUE THREAD

**Issue by mazraara** [stackkit/laravel-database-emails#12]
On laravel 5.7 it does not work with '--timeout' option. 

eg:     $schedule->command('email:send', ['--timeout' => 300])->everyMinute()->withoutOverlapping(5);

https://stackkit.github.io/laravel-database-emails/installation/

**Comment by marickvantuil** [comment]
Thats correct because ive removed this option in 4.0.0 but documentation wasn't updated yet. I've moved the documentation back to the README.md file

**Comment by mazraara** [comment]
Thanks it looks good now.
