### ISSUE TITLE
A few suggestions ...

### ISSUE THREAD

**Issue by SundialServices** [stackkit/laravel-database-emails#28]
First of all, I just used this package with *excellent* success – thank you! – on a Laravel project where it definitely saved me at least a full month of drudgery.  Based on this experience I'd like to offer a few suggestions:

(1) I had to override the Composer class to add methods **to()** and **body()**.  "to" as a synonym for "recipient."  "body" as a way to supply the body-content without a template.  (I overrode the Mail class to return my customized Composer subclass.)

(2) Although "body" was populated, the Validator still objected – "no view specified."  If the body has been specified, no view is required.  The validator ought not have objected.  (I had to specify an existing view-name even though it's never used.)  Of course I understand that this is a consequence of the new method I'd added.

(3) FYI:  It was enormously beneficial to me that the `setData()` method simply allows "any key."  When the requirement came up to be able to determine *which one* of our Laravel systems had queued a particular message, I was able to say, "no problem!"  Just define a custom-key and "done."  Very nice.

(4) For those reading this who might be curious, I overcame the fact that the fields are BLOBs, in MySQL, with `convert(recipient using latin1) like ...` in my search-tool.  (I agree that they should be BLOBs ...)

Once again, a very fine piece of software – more comprehensive than I actually required, and very much appreciated.  Thanks for taking the time to write this, to write it so well, and to share it.

**Comment by marickvantuil** [comment]
Hi, thanks for this nice message! I'm glad you find the package helpful. I like the idea of those features and can definitely see them being useful for the package. Feel free to send a PR if you need them added quick, otherwise I'll get to it at some point.

Thanks!
