### ISSUE TITLE
Always expecting a view

### ISSUE THREAD

**Issue by jamesautodude** [stackkit/laravel-database-emails#45]
When using:

Email::compose()
    ->mailable(new OrderShipped())
    ->send();

I get an error of:
View [] not found.

**Comment by jamesautodude** [comment]
I haven't heard anything back :/ but that's alright

For anyone else, the workaround is just to not use this since I guess it's not going to be fixed :/

### Before package example
For reference, this is how I was doing it before the package

I use the database to store my mailable templates so, this is how I do that with regular laravel:

```
//use helper to grab the subject from mailable table with column "mailable" as "ClientSignup" and column "subject"
$subject = emailTemplate($companyInfo->id, 'ClientSignup', 'subject'); 

//use helper to grab the body from mailable table with column "mailable" as "ClientSignup" and column "html_template"
$body = emailTemplate($companyInfo->id, 'ClientSignup', 'body');

Mail::to($request->email)->send(new DatabaseMailer($body, $subject));
```

The above Mail::to works perfectly

### What I expected I could do it with this package
Based on readme I though I could do the following...

```
//use helper to grab the subject from mailable table with column "mailable" as "ClientSignup" and column "subject"
$subject = emailTemplate($companyInfo->id, 'ClientSignup', 'subject'); 

//use helper to grab the body from mailable table with column "mailable" as "ClientSignup" and column "html_template"
$body = emailTemplate($companyInfo->id, 'ClientSignup', 'body');

Email::compose()
->mailable(new DatabaseMailer($body, $subject))
->send();
```

Unfortunately it gives `View[] not found`

### Workaround
I will use the following for now, which isn't a bad thing... just posting for reference

```
//use helper to grab the subject from mailable table with column "mailable" as "ClientSignup" and column "subject"
$subject = emailTemplate($companyInfo->id, 'ClientSignup', 'subject'); 

//use helper to grab the body from mailable table with column "mailable" as "ClientSignup" and column "html_template"
$body = emailTemplate($companyInfo->id, 'ClientSignup', 'body');

Email::compose()
  ->label('welcome')
  ->recipient('test@gmail.com')
  ->subject('This is a test')
  ->view('emails.databaseTemplate')
  ->variables([
      'subject' => $subject,
      'body' => $body,
  ])
  ->send();
```

This workaround works fine

Thank you

**Comment by marickvantuil** [comment]
Sorry, I can't reproduce this using fresh installs of Laravel 8, 9 or 10! Few questions:

- Which package version, PHP version and Laravel version are you using?
- What does the mailable look like?
